# Generated by Django 3.0.4 on 2020-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Photo',
            field=models.ImageField(upload_to='manager_owner'),
        ),
    ]
